services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: citrus_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www
    environment:
      - APP_ENV=local
      - DB_HOST=postgres
    healthcheck:
      test: [ "CMD", "php", "-r", "exit(0);" ]
      interval: 10s
      retries: 5
      start_period: 10s
    depends_on:
      - mysql
      - postgres
    networks:
      - citrus_network

  nginx:
    image: nginx:latest
    container_name: citrus_nginx
    restart: unless-stopped
    ports:
      - "8000:80"
    working_dir: /var/www/html
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - citrus_network

  mysql:
    image: mysql:8
    container_name: citrus_mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: citrus
      MYSQL_USER: citrus
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - citrus_network

  postgres:
    image: postgres:15
    container_name: citrus_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: citruse
      POSTGRES_USER: citruse
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - citrus_network

networks:
  citrus_network:

volumes:
  mysql_data:
  postgres_data:
